### PR TITLE
refactor: Improve Mouser link in BOM for kitspace

### PR DESCRIPTION
**Pull request by kasbah**
Hey, [Kitspace page is up](https://kitspace.org/boards/github.com/hutscape/oak/)! 

By using this link for the Mouser part it will get picked up on the page for 1-click buying. It's the exact same part but just a different link (the exact Mouser SKU is in the new link, which is how Kitspace processes it).

### CODE REVIEW

**Comment by sayanee** [comment]
@kasbah Thanks once again! I do try to keep the URLs clean but didn't know about this mouser link. I will take note about this in the future 🙇🏼‍♀️

**Comment by kasbah** [comment]
Not sure why Mouser has the same pages under different URLs and don't just redirect to one canonical URL :man_shrugging:

**Comment by sayanee** [comment]
> Kitspace pages are re-building every 3 hours now

@kasbah Does this mean, if I make a change in the BOM `CSV` file or the Gerber files, Kitspace will automatically pick it up? Do the Gerbers get automatically picked up from the [GitHub releases](https://github.com/hutscape/oak/releases). I have git-ignored them in this repository but I add to the tag releases instead.

Sorry, I did not find any documentation on updating projects. I might have missed it on kitspace.org.

I might have some minor changes to the BOM (an alternative to the mouser URL) or even have some fixes in the PCB layout. I'll release the updated Gerbers as usual.

**Comment by kasbah** [comment]
Yes, sorry, it's not well documented but it will keep updating with your repo. We don't support grabbing files from Github releases yet, only whatever is in your repo. The Gerbers we have on Kitspace are automatically plotted from your `.kicad_pcb`.  You can override this and use your own Gerbers but right now you would have to add them to the Git repo.

**Pull request merged**
